topics:
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 8
- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 1
- name    : hand_drive
  topic   : /cmd_hand_drive
  timeout : 0.5
  priority: 100
- name    : e_stop
  topic   : /stop
  timeout : 0.5
  priority: 255 

